### ISSUE TITLE
zlib.error when running next(records)

### ISSUE THREAD

**Issue by Superraptor** [dimazest/google-ngram-downloader#17]
Hi! So I'm getting the following traceback:

```
Traceback (most recent call last):
  File "./auxiliary_files/nlp.py", line 179, in <module>
    if __name__ == "__main__": main()
  File "./auxiliary_files/nlp.py", line 41, in main
    words_unit_tests("29224256", "CDK4 Gene Amplification")
  File "./auxiliary_files/nlp.py", line 166, in words_unit_tests
    print(count_google_ngrams_occurrences_of_word(word, ngram_length=2))
  File "./auxiliary_files/nlp.py", line 148, in count_google_ngrams_occurrences_of_word
    record = next(records)
  File "D:\ProgramData\Anaconda3\lib\site-packages\google_ngram_downloader\util.py", line 41, in lines
    chunk = dec.decompress(compressed_chunk)
zlib.error: Error -3 while decompressing data: incorrect header check
```

Basically this happens when I'm trying to run:

```
    fname, url, records = next(readline_google_store(ngram_len=ngram_length, indices=word[0], verbose=True))
        
    try:
        record = next(records)
        while record.ngram != word:
            record = next(records)
        while record.ngram == word:
            count = count + record.match_count
            record = next(records)
    except StopIteration as e:
        pass
    return count
```

This is using Python 3.6.5, 64-bit Windows operating system. I tried using some of the decompression techniques [here ](https://stackoverflow.com/questions/3122145/zlib-error-error-3-while-decompressing-incorrect-header-check) but to no avail thus far... Any help would be much appreciated! Thanks so much for a great package!

**Comment by dimazest** [comment]
Hi, what's the values of `ngram_length` and `word[0]`?

**Comment by Superraptor** [comment]
Sorry for taking so long to respond! `ngram_length` is 2 and `word[0]` is 'C'.

**Comment by Superraptor** [comment]
Okay... So I changed the index to `cd` (the first two letters of the word I'm looking up, and I still get the error: 

```
Traceback (most recent call last):
  File "./auxiliary_files/nlp.py", line 192, in <module>
    if __name__ == "__main__": main()
  File "./auxiliary_files/nlp.py", line 41, in main
    words_unit_tests("29224256", "CDK4 Gene Amplification")
  File "./auxiliary_files/nlp.py", line 179, in words_unit_tests
    print(count_google_ngrams_occurrences_of_word(word, ngram_length=2))
  File "./auxiliary_files/nlp.py", line 159, in count_google_ngrams_occurrences_of_word
    record = next(records)
  File "D:\ProgramData\Anaconda3\lib\site-packages\google_ngram_downloader\util.py", line 41, in lines
    chunk = dec.decompress(compressed_chunk)
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by dimazest** [comment]
Try passing a list, that is `['cd']`.
